### ISSUE TITLE
License for rb?

### ISSUE THREAD

**Issue by DrDub** [marineb/rockaway-beach#1]
Hi,

What license applies to this project? Is it available under an open source license?

Best regards,

P

**Comment by marineb** [comment]
Hi @DrDub, let me get back to you on that later today. Just out of curiosity, what was appealing to you in that repo?

**Comment by DrDub** [comment]
Just looking for something interesting to contribute as part of 24PR.

**Comment by marineb** [comment]
Awesome. OK. Added the [license](https://github.com/marineb/rockaway-beach/blob/master/LICENSE.md)! Let me know if you need anything.
